### ISSUE TITLE
64 bit is not supported 

### ISSUE THREAD

**Issue by hussain1982** [jzdziarski/nestopia#21]
Beginning June 1, 2015 All iOS apps app updates submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK.  New Apps must included 64 bit support since February 2015 .

So Nestopia is working fine if the architectures is 32 bit , but its crash and not working correctly if we use Standard architectures that support 64 bit & 32 bit in Xcode .

So could you please help and make an update to fix this issue and to support iOS 8 and 64 bit architectures .

**Comment by jzdziarski** [comment]
The Nestopia core does not presently support arm64. The Nestopia dev team would need to address this.
